[pytest]
markers =
    smoke: marks tests as smoke
    regress: marks tests as regress
    extended: marks tests as extended
    all: marks tests as all
    first_test: marks first_test
    second_test: marks first_test