[Interface]
PrivateKey = aLXI448ncPlpvLYPERnh81jbabA7rh0u6ZSbi2r+p0s=
ListenPort = 51820
Address = 10.10.251.15/32
DNS = 8.8.8.8, 1.1.1.1  # Используем публичные DNS

[Peer]
PublicKey = xC1T9uolyc5vrLHWGUTaeWzeRgl8kMj5F8F5Q/F5wVo=
PresharedKey = WKkKcQ+sEWPyV4IQtLbFdPzb5wN4eAnv/4w7lziLJ0I=
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1, ::/1, 8000::/1
Endpoint = 109.235.189.130:13231
PersistentKeepalive = 25
